onboro/urls.py
from django.urls import path

from . import views

app_name = 'onboro'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),

    path('users', views.UserIndexView.as_view(), name='user_index'),
    path('users/<int:pk>', views.UserDetailView.as_view(), name='user_detail'),
    path('users/import', views.user_import, name='user_import'),

    path('search', views.BookSearchView.as_view(), name='book_search'),
    path('books/<int:pk>', views.BookDetailView.as_view(), name='book_detail'),
    path('books/<int:book_id>/chapters/<int:number>', views.BookChapterView.as_view(), name='book_chapter'),

    path('users/<int:pk>/transactions/charge', views.transaction_charge, name='transaction_charge'),
    path('users/<int:pk>/transactions/use', views.transaction_use, name='transaction_use'),

    path('purchase/', views.CoinPurchaseView.as_view(), name='coin_purchase'),
    path('favorite/<int:pk>/toggle', views.toggle_favorite, name='toggle_favorite'),
    path('favorites/', views.FavoriteBookListView.as_view(), name='favorite_book_list'),
]

sample5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('onboro.urls')),
    path('admin/', admin.site.urls),
]

onboro/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    coin = models.IntegerField(default=0, verbose_name='コイン')

    books = models.ManyToManyField(
        # まだ定義してないので文字列で指定する必要がある
        'Book',
        through='TransactionRecord'
    )

class Category(models.Model):
    display_order = models.IntegerField(verbose_name='表示順')
    name = models.CharField(max_length=80, verbose_name='名前')

    class Meta:
        ordering = ['display_order']

        verbose_name = 'カテゴリ'
        verbose_name_plural = 'カテゴリ'

    def __str__(self):
        return self.name

class Book(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    title = models.CharField(max_length=80, verbose_name='タイトル')
    abstract = models.TextField(verbose_name='概要')
    price = models.PositiveIntegerField(verbose_name='価格')
    published = models.BooleanField('公開')
    favorite_users = models.ManyToManyField(User, related_name='favorite_books', blank=True)


    class Meta:
        verbose_name = '書籍'
        verbose_name_plural = '書籍'

    def __str__(self):
        return self.title

class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, verbose_name='書籍')
    number = models.PositiveIntegerField(verbose_name='章番号')
    title = models.CharField(max_length=80, verbose_name='章名')
    body = models.TextField(verbose_name='本文')

    class Meta:
        ordering = ['number']

        verbose_name = '章'
        verbose_name_plural = '章'

    def __str__(self):
        return self.title

    def title_with_number(self):
        return f'第{self.number}章 {self.title}'

    def next_chapter(self):
        return self.book.chapter_set.filter(number=self.number+1).first()

    def prev_chapter(self):
        return self.book.chapter_set.filter(number=self.number-1).first()

class TransactionRecord(models.Model):
    class Kind(models.IntegerChoices):
        CHARGE = (1, 'チャージ')
        USE = (2, '使用')

    kind = models.IntegerField(choices=Kind.choices, verbose_name='種類')
    amount = models.PositiveIntegerField(verbose_name='金額')
    # 取引記録がある場合、削除はできなくする
    user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='ユーザー')
    book = models.ForeignKey(Book, null=True, blank=True, on_delete=models.PROTECT, verbose_name='書籍')
    datetime = models.DateTimeField(verbose_name='日時')

    class Meta:
        verbose_name = '取引記録'
        verbose_name_plural = '取引記録'

onboro/forms.py
from django import forms

from .models import Category, TransactionRecord

class UserImportForm(forms.Form):
    file = forms.FileField(
        widget=forms.FileInput(attrs={'accept': 'text/csv'})
    )

class BookSearchForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)
    word = forms.CharField(required=False, widget=forms.TextInput(attrs={'type': 'search'}))

class CoinChargeForm(forms.ModelForm):
    class Meta:
        model = TransactionRecord
        fields = ['amount', 'user']
        widgets = {
            'user': forms.HiddenInput
        }

class CoinUseForm(forms.ModelForm):
    class Meta:
        model = TransactionRecord
        fields = {'user', 'book'}
        widgets = {
            'user': forms.HiddenInput,
            'book': forms.HiddenInput
        }


class CoinPurchaseForm(forms.Form):
    amount=forms.IntegerField(label="購入するコインの枚数",min_value=1)

onboro/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views import generic
from django.contrib.auth import views as auth_views
from django.contrib.auth import mixins as auth_mixins
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.db import transaction, IntegrityError
from django.db.models import Q
from django.utils import timezone
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

import csv
import codecs

from .models import User, Book, TransactionRecord
from .forms import UserImportForm, BookSearchForm, CoinChargeForm, CoinUseForm,CoinPurchaseForm

# Create your views here.
class BookSearchMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # フォームの初期値として「送信された検索条件」を設定
        context['search_form'] = BookSearchForm(self.request.GET)
        return context

class HomeView(BookSearchMixin, generic.TemplateView):
    template_name = 'onboro/home.html'

class LoginView(auth_views.LoginView):
    template_name = 'onboro/login.html'

class LogoutView(auth_views.LogoutView):
    pass

def staff_required(user):
    return user.is_staff

class StaffRequiredMixin(auth_mixins.UserPassesTestMixin):
    def test_func(self):
        return staff_required(self.request.user)

class UserIndexView(StaffRequiredMixin, generic.ListView):
    queryset = User.objects.filter(is_staff=False)
    template_name = 'onboro/user_index.html'
    context_object_name = 'users'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['import_form'] = UserImportForm()
        return context

class UserDetailView(StaffRequiredMixin, generic.DetailView):
    queryset = User.objects.filter(is_staff=False)
    template_name = 'onboro/user_detail.html'
    # userという名前はdjango.contrib.authにより設定されるので使えない
    context_object_name = 'object'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['charge_form'] = CoinChargeForm(initial={'user': self.kwargs['pk']})
        return context

# 関数として定義しておいた「スタッフ権限が必要」を使い、一般ユーザーはアクセスできないようにします
@user_passes_test(staff_required)
def user_import(request):
    if request.method == 'POST':
        # 「ファイル内容」以外はPOSTに格納されるので両方を指定します
        form = UserImportForm(request.POST, request.FILES)
        if form.is_valid():
            # validation実行後はcleaned_dataに内容が設定されます
            file = form.cleaned_data['file']
            # fileはバイナリオープンされるのでCSVで読み込むにはdecodeが必要
            reader = csv.DictReader(codecs.iterdecode(file, 'utf-8'))

            try:
                # トランザクションとして実行（一つでもエラーになる場合は全部の追加を取りやめる）
                # with文を使い、その内部に「処理」を書く
                with transaction.atomic():
                    for row in reader:
                        # is_activeはint経由でboolに変換
                        row['is_active'] = bool(int(row['is_active']))
                        # Userはパスワードについて特別処理が必要なため、専用のcreate_userメソッドが用意されている
                        # usernameは一意である必要があるため、同じusernameがあるとIntegrityError（例外）が発生する
                        User.objects.create_user(**row)
                messages.success(request, 'インポートに成功しました。')
            except IntegrityError:
                messages.error(request, 'インポートが行えませんでした。ユーザー名が重複している可能性があります。')

    return redirect('onboro:user_index')

class BookSearchView(BookSearchMixin, generic.ListView):
    template_name = 'onboro/book_search.html'
    context_object_name = 'books'

    def get_queryset(self):
        # BookSearchFormは使わず、直接取得する方がわかりやすい
        category = self.request.GET.get('category')
        word = self.request.GET.get('word')

        # 公開しているもののみを対象とする
        books = Book.objects.filter(published=True)
        # カテゴリが設定されていれば条件に加える
        if category:
            books = books.filter(category__pk=category)
        # 検索ワードが指定されていれば条件に加える
        # タイトルと概要は「どちらかに書いてあれば（OR）」でカテゴリとはANDとなる
        if word:
            q1 = Q(title__contains=word)
            q2 = Q(abstract__contains=word)
            books = books.filter(q1 | q2)

        return books

def can_view_chapter(user, book_id):
    if user.is_authenticated:
        if user.is_staff:
            return True
        if user.books.filter(pk=book_id).exists():
            return True

    return False

class BookDetailView(BookSearchMixin, generic.DetailView):
    queryset = Book.objects.filter(published=True)
    template_name = 'onboro/book_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # ユーザーが書籍を購入していなければ購入フォームを用意する
        user = self.request.user
        book_pk = self.kwargs['pk']
        if user.is_authenticated:
            if not user.books.filter(pk=book_pk).exists():
                context['use_form'] = CoinUseForm(initial={
                    'user': user.pk,
                    'book': book_pk
                })
            context['is_favorited'] = user.favorite_books.filter(pk=book_pk).exists()

        context['can_view_chapter'] = can_view_chapter(user, book_pk)

        return context

class BookChapterView(BookSearchMixin, generic.DetailView):
    template_name = 'onboro/book_chapter.html'

    def get(self, request, *args, **kwargs):
        # 購入していない書籍の章に直アクセスされたら403を返す
        book_id = self.kwargs['book_id']
        if not can_view_chapter(self.request.user, book_id):
            return HttpResponseForbidden()

        return super().get(request, args, kwargs)

    # 指定bookの中の指定chapterなのでget_objectを定義する必要あり
    def get_object(self, queryset=None):
        book_id = self.kwargs['book_id']
        number = self.kwargs['number']
        # 非公開のbookにはアクセスできないようにする
        book = get_object_or_404(Book, pk=book_id, published=True)
        # 存在しない章にアクセスされたとき対策としてこちらもget_or_404を使う
        # get_or_404にはManagerを渡せる
        chapter = get_object_or_404(book.chapter_set, number=number)
        return chapter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get_objectでchapter返すのでchapterが設定される
        chapter = context['chapter']
        # chapterの親もcontextにあった方がいいので設定
        context['book'] = chapter.book
        return context

@user_passes_test(staff_required)
def transaction_charge(request, pk):
    if request.method == 'POST':
        form = CoinChargeForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            # 予想外のことがない限り例外は発生しないのでtry-exceptはしない
            with transaction.atomic():
                user = record.user
                user.coin += record.amount
                user.save()

                record.kind = TransactionRecord.Kind.CHARGE.value
                record.datetime = timezone.now()
                record.save()

    return redirect('onboro:user_detail', pk)

def transaction_use(request, pk):
    # リダイレクト先がbook_detailなのでGETされるのは想定外（Django的にエラーにする）
    if request.method == 'POST':
        form = CoinUseForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            user = record.user
            book = record.book

            if user.coin < book.price:
                messages.warning(request, 'コインが足りません。')
                # コード重複にはなるがインデントが深くなるとわかりにくくなるのでここでreturn
                return redirect('onboro:book_detail', book.pk)

            with transaction.atomic():
                user.coin -= book.price
                user.save()

                record.kind = TransactionRecord.Kind.USE.value
                record.amount = book.price
                record.datetime = timezone.now()
                record.save()

    return redirect('onboro:book_detail', book.pk)

class CoinPurchaseView(auth_mixins.LoginRequiredMixin, generic.FormView):
    template_name = 'onboro/purchase.html'
    form_class = CoinPurchaseForm
    success_url = reverse_lazy('onboro:home')

    def form_valid(self, form):
        amount = form.cleaned_data['amount']
        user = self.request.user

        with transaction.atomic():
            user.coin += amount
            user.save()

            TransactionRecord.objects.create(
                kind=TransactionRecord.Kind.CHARGE,
                amount=amount,
                user=user,
                datetime=timezone.now()
            )

        messages.success(self.request, f'{amount}コインを購入しました。')
        return super().form_valid(form)

@login_required
def toggle_favorite(request, pk):
    book = get_object_or_404(Book, pk=pk)
    user = request.user
    if user.favorite_books.filter(pk=pk).exists():
        user.favorite_books.remove(book)
    else:
        user.favorite_books.add(book)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', reverse('onboro:book_detail', kwargs={'pk': pk})))


class FavoriteBookListView(auth_mixins.LoginRequiredMixin, generic.ListView):
    template_name = 'onboro/favorite_book_list.html'
    context_object_name = 'books'

    def get_queryset(self):
        return self.request.user.favorite_books.all()

onboro/templates/onboro/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
　　<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'onboro/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'onboro/css/custom.css' %}">
    <title>{% block title %}Book On{% endblock %}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Book On</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                {# ここに検索フォームを追加します #}
                {% if search_form %}
	                <form class="d-flex" action="{% url 'onboro:book_search' %}" method="get">
	                    <div class="input-group">
	                        {{ search_form.category|add_class:"form-select" }}
	                        {{ search_form.word|add_class:"form-control me-2" }}
	                    </div>
	                    <button class="btn btn-outline-success" type="submit">Search</button>
	                </form>
                {% endif %}

                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'onboro:favorite_book_list' %}" class="nav-link">
                                お気に入り
                            </a>
                        </li>
                        {# ログインしている場合は誰でログインしているか表示し、ログアウトリンクを出力 #}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown">
                                {{ user.username }}
                            </a>
                            <ul class="dropdown-menu">
                                <form action="{% url 'onboro:logout' %}" method="post">
                                    {% csrf_token %}
                                    <input type="submit" value="ログアウト" class="dropdown-item">
                                </form>
                            </ul>
                        </li>
                    {% else %}
                        {# ログインしていない場合はログインリンクを表示 #}
                        <li class="nav-item">
                            <a href="{% url 'onboro:login' %}" class="nav-link">
                                ログイン
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block contents %}
        {% endblock %}
    </div>
    <script src="{% static 'onboro/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

onboro/templates/onboro/book_chapter.html
{% extends 'onboro/base.html' %}

{% block title %}
{{ chapter.title_with_number }} | {{ book.title }} | {{ block.super }}
{% endblock %}

{% block contents %}

<h1 class="my-3">
    <a href="{% url 'onboro:book_detail' book.pk %}">
        {{ book.title }}
    </a>
</h1>
<h2 class="my-3">{{ chapter.title_with_number }}</h2>

<div class="book-body">
    {{ chapter.body|linebreaks }}
</div>

<ul class="nav mt-3">
    {# 前の章があったら表示 #}
    {% with prev_chapter=chapter.prev_chapter %}
        {% if prev_chapter %}
            <li class="nav-item me-auto">
                <a href="{% url 'onboro:book_chapter' book.id prev_chapter.number %}" class="nav-link">
                    &laquo; {{ prev_chapter.title_with_number }}
                </a>
            </li>
        {% endif %}
    {% endwith %}

    {# 次の章があったら表示 #}
    {% with next_chapter=chapter.next_chapter %}
        {% if next_chapter %}
            <li class="nav-item ms-auto">
                <a href="{% url 'onboro:book_chapter' book.id next_chapter.number %}" class="nav-link">
                    {{ next_chapter.title_with_number }} &raquo;
                </a>
            </li>
        {% endif %}
    {% endwith %}
</ul>

{% endblock %}

onboro/templates/onboro/book_detail.html
{% extends 'onboro/base.html' %}
{% load humanize %}

{% block title %}
{{ book.title }} | {{ block.super }}
{% endblock %}

{% block contents %}

<h1 class="my-3">{{ book.title }}</h1>
<div class="mb-3">
    カテゴリ：{{ book.category.name }}
</div>
<div class="mb-3">
    価格：{{ book.price|intcomma }}
</div>
<div>
    概要：
    <div class="ms-3">
        {{ book.abstract|linebreaks }}
    </div>
</div>

<ul class="nav flex-column">
    {% for chapter in book.chapter_set.all %}
        <li class="nav-item">
            {% if can_view_chapter %}
            <a href="{% url 'onboro:book_chapter' book.pk chapter.number %}" class="nav-link">
                {{ chapter.title_with_number }}
            </a>
            {% else %}
            <a href="{% url 'onboro:book_chapter' book.pk chapter.number %}" class="nav-link disabled">
                {{ chapter.title_with_number }}
            </a>
            {% endif %}
        </li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
    <div class="mt-3">
    {% if is_favorited %}
        <a href="{% url 'onboro:toggle_favorite' book.pk %}" class="btn btn-warning">お気に入りから削除</a>
    {% else %}
        <a href="{% url 'onboro:toggle_favorite' book.pk %}" class="btn btn-outline-warning">お気に入りに追加</a>
    {% endif %}
    </div>

    {% if use_form %}
        <form action="{% url 'onboro:transaction_use' user.pk %}" method="post" class="mt-3">
            {% csrf_token %}
            {{ use_form }}
            <input type="submit" value="購入" class="btn btn-primary">
        </form>
        {% include 'onboro/messages.html' %}
    {% else %}
        <div class="card text-dark bg-light mt-3">
            <div class="card-body">
                購入済み
            </div>
        </div>
    {% endif %}
{% endif %}

{% endblock %}

onboro/templates/onboro/book_search.html
{% extends 'onboro/base.html' %}
{% load humanize %}

{% block contents %}

<table class="table mt-3">
    <thead>
        <tr>
            <th>カテゴリ</th>
            <th>書名</th>
            <th>価格</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.category.name }}</td>
                <td>
                    <a href="{% url 'onboro:book_detail' book.pk %}">
                        {{ book.title }}
                    </a>
                </td>
                <td>{{ book.price|intcomma }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

onboro/templates/onboro/favorite_book_list.html
{% extends 'onboro/base.html' %}
{% load humanize %}

{% block title %}
お気に入り一覧 | {{ block.super }}
{% endblock %}

{% block contents %}

<h1 class="my-3">お気に入り一覧</h1>

<table class="table mt-3">
    <thead>
        <tr>
            <th>カテゴリ</th>
            <th>書名</th>
            <th>価格</th>
        </tr>
    </thead>
    <tbody>
        {% for book in books %}
            <tr>
                <td>{{ book.category.name }}</td>
                <td>
                    <a href="{% url 'onboro:book_detail' book.pk %}">
                        {{ book.title }}
                    </a>
                </td>
                <td>{{ book.price|intcomma }}</td>
            </tr>
        {% empty %}
            <tr>
                <td colspan="3">お気に入りに登録された書籍はありません。</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

onboro/templates/onboro/home.html
{% extends 'onboro/base.html' %}
{% load humanize %}

{% block contents %}

{% if user.is_authenticated %}

<h1 class="mt-3">本棚</h1>
<table class="table">
    <thead>
        <tr>
            <th>カテゴリ</th>
            <th>書名</th>
        </tr>
    </thead>
    <tbody>
        {% for book in user.books.all %}
            <tr>
                <td>{{ book.category.name }}</td>
                <td>
                    <a href="{% url 'onboro:book_detail' book.pk %}">
                        {{ book.title }}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="mb-3">
    保有コイン：{{ user.coin|intcomma }}
    <a href="{% url 'onboro:coin_purchase' %}" class="btn btn-primary btn-sm ms-2">コインを購入する</a>
</div>

<h1>取引記録</h1>
{% include 'onboro/transaction_records.html' with transaction_records=user.transactionrecord_set.all %}

{% endif %}

{% endblock %}

onboro/templates/onboro/login.html
{% extends 'onboro/base.html' %}
{% load widget_tweaks %}

{% block contents %}

<form method="post" class="mt-3">
    {% csrf_token %}

    <div class="mb-3">
        {{ form.username|add_label_class:"form-label" }}
        {{ form.username|add_class:"form-control" }}
    </div>
    <div class="mb-3">
        {{ form.password|add_label_class:"form-label" }}
        {{ form.password|add_class:"form-control" }}
    </div>
    <input type="submit" class="btn btn-primary" value="ログイン">

    {# フィールド以外のエラー（ログイン失敗など）を表示 #}
    {% if form.non_field_errors %}
        <div class="card bg-warning mt-3">
            <div class="card-body">
                {% for error in form.non_field_errors %}
                    <div class="card-text">{{ error }}</div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</form>

{% endblock %}

onboro/templates/onboro/messages.html
{% if messages %}
    {# 繰り返しはするが実際には一つ #}
    {% for message in messages %}
        <div class="card mt-3 {{ message.tags }}">
            <div class="card-body">{{ message }}</div>
        </div>
    {% endfor %}
{% endif %}

onboro/templates/onboro/purchase.html
{% extends 'onboro/base.html' %}
{% load widget_tweaks %}

{% block contents %}

<h1 class="my-3">コインの購入</h1>

<form method="post">
    {% csrf_token %}
    <div class="mb-3">
        {{ form.amount|add_label_class:"form-label" }}
        {{ form.amount|add_class:"form-control" }}
    </div>
    <button type="submit" class="btn btn-primary">購入する</button>
</form>

{% endblock %}

onboro/templates/onboro/transaction_records.html
{% load humanize %}

<table class="table">
    <thead>
        <tr>
            <th>種別</th>
            <th>金額</th>
            <th>日時</th>
        </tr>
    </thead>
    <tbody>
        {% for record in transaction_records %}
            <tr>
                <td>
                    {{ record.get_kind_display }}
                    {% if record.book %}
                        （<a href="{% url 'onboro:book_detail' record.book.pk %}">{{ record.book }}</a>）
                    {% endif %}
                </td>
                <td>{{ record.amount|intcomma }}</td>
                <td>{{ record.datetime }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

onboro/templates/onboro/user_detail.html
{% extends 'onboro/base.html' %}
{% load widget_tweaks %}
{% load humanize %}

{% block title %}
{{ object.username }} | {{ block.super }}
{% endblock %}

{% block contents %}

<div class="my-3">
    <a href="{% url 'onboro:user_index' %}">一覧に戻る</a>
</div>

<table class="table">
    <tbody>
        <tr>
            <th>ユーザー名</th>
            <td>{{ object.username }}</td>
        </tr>
        <tr>
            <th>有効</th>
            <td>{{ object.is_active }}</td>
        </tr>
    </tbody>
</table>

<div class="my-3">
    コイン：{{ object.coin|intcomma }}
</div>

<form action="{% url 'onboro:transaction_charge' object.pk %}" method="post" class="mb-3">
    {% csrf_token %}
    {{ charge_form.user }}
    <div class="mb-3">
        {{ charge_form.amount|add_class:"form-control" }}
    </div>
    <input type="submit" value="追加" class="btn btn-primary">
</form>

{% include 'onboro/transaction_records.html' with transaction_records=object.transactionrecord_set.all %}

{% endblock %}

onboro/templates/onboro/user_index.html
{% extends 'onboro/base.html' %}
{% load widget_tweaks %}

{% block contents %}

<table class="table">
    <thead>
        <tr>
            <th>ユーザー名</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
            <tr>
                <td>
                    <a href="{% url 'onboro:user_detail' user.id %}">
                        {{ user.username }}
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<form action="{% url 'onboro:user_import' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
        {{ import_form.file|add_class:"form-control" }}
    </div>
    <input type="submit" value="インポート" class="btn btn-primary">
</form>

{% include 'onboro/messages.html' %}

{% endblock %}